# Site settings
baseurl = "http://wolfapple.github.io/"
languageCode = "en-us"
title = "Barney Kim"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-29458529-2"
# Disable comments by leaving disqusShortname empty
disqusShortname = "wolfapple"

[params]
  name = "Barney Kim"
  description = "Blog"
  bio = "Blogger - Programmer - Gopher"
  # Enter optionally your twitter account
  twitter = "wolfapple"
  enableRSS = true

  # Add custom assets with their paths relative to the static folder
  customCSS = []
  customJS  = []

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.

  # Navigation links
  home = ""
  about = ""
  subscribe = ""
  # Pagination links
  olderPosts = ""
  newerPosts = ""
  readMore = ""
  copyright = ""
  # Sharing options and author information in posts
  aboutAuthor = "I'm an enthusiastic gopher."
  tweet = ""
  share = ""
  # 404 page
  title404 = ""
  subtitle404 = ""

  # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
  iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/wolfapple"
    facebook = "https://www.facebook.com/wolfapple"
    github   = "https://www.github.com/wolfapple"